ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Decisiones de Arquitectura

.Tecnologías para el backend

Se ha decidido usar las tecnologías Node.js y React para llevar a cabo la programación del programa y la 
página en la que se va a usar.

Esto se debe, en gran medida, debido a que iniciamos desde un proyecto ya creado, el cual usa estas dos tecnologías.
Por ello, para evitar perder tiempo intentando cambiar el código funcional ya existente, se ha decidido mantener el uso
de estas tecnologías en los servicios a realizar.

Base de Datos::

Para el manejo de datos, como los usuarios, se ha decidido el uso de la tecnología de MongoDB. Esta es una tecnología
compatible con las ya aceptadas del proyecto dado y es una con la que todos, o por lo menos la gran mayoría de los miembros
del grupo, estamos acostumbrados a usar.

También, debido al tipo de los datos a guardar en la base de datos se ha pensado y aceptado por los usuarios que la mejor 
opción para guardarlos es usando una base de datos NoSQL, cosa de la MongoDB se especializa.


