ifndef::imagesdir[:imagesdir: ../images]

[[section-test-report]]
== Informe de pruebas

=== Pruebas unitarias

Para este proyecto decidimos hacer pruebas unitarias para cada servicio creado y para cada componente de react del frontend.
Estas pruebas se ejecutan obligatoriamente al realizar un commit en la rama main del repositorio y al hacer una release permitiendo asegurarnos del correcto funcionamiento de la aplicación.

==== Pruebas servicios

Este proyecto consta de 6 servicios, Gateway , User , Auth , Generator , Question y Statistics.

Gateway::

Las pruebas de este servicio constan de probar que las diferentes rutas al resto de servicios estén disponibles y retornen los datos correctos. Ademas también se prueban casos de errores
En total se realizan 46 pruebas.

User:: 

Para este servicio se prueba que se registre bien los usuarios almacenando sus datos. También se prueba caso negativo de que no se introduzcan todos los campos.
En total se realizan 3 pruebas.
Auth::

Este servicio se prueba que el acceso de usuario sea correcto cuando los credenciales sean correctas. En total se realizan 3 pruebas.

Generartor::

Las pruebas unitarias de este servicio constan de probar que a partir de las plantillas de preguntas se haga la consulta a la api y se le de el formato correcto al resultado.
En total se realizan 10 pruebas.

Question:: 

Las pruebas de este servicio nos asegura que sea capaz de retornar las diferentes preguntas generadas. Tiene una única prueba.

Statistics:: 

Las pruebas unitarias de este servicio se encargan de probar a obtener las estadísticas del los usuarios con el formato correcto.En total se realizan 7 pruebas.

==== Pruebas Webapp

En la aplicación se realizó pruebas en cada uno de los componentes de react donde se realizan 12 conjuntos de prueba con un total de 40 pruebas ejecutadas.

=== Pruebas de aceptación

Se han realizado un total de 2 pruebas de aceptación con puppeteer. Las pruebas fueron realizadas para la acción de iniciar sesión y de registro.

Registro:: 

Para probar el registro se rellenan todos los campos del registro y se presiona el botón, posteriormente se comprueba que exista el usuario en la base de datos.

Inicio de sesión::

Para el inicio de sesión se introduce un usuario en la base de datos y posteriormente se prueba el registro introduciendo el usuario y la contraseña. 


=== Cobertura de código 

Con las pruebas unitarias se puede observar el porcentaje del código se ha cubierto con estas. Para este proyecto decidimos usar el quality gate de aws donde se necesita mas de un 80% de cobertura.

=== Pruebas de carga 
